
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LPAR = 5;
  public static final int STRING_LITERAL = 13;
  public static final int PLUS = 11;
  public static final int EOF = 0;
  public static final int PREFIX = 3;
  public static final int IF = 9;
  public static final int ID = 12;
  public static final int ELSE = 10;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int RPAR = 6;
  public static final int SUFFIX = 2;
  public static final int END = 8;
  public static final int BEGIN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUFFIX",
  "PREFIX",
  "COMMA",
  "LPAR",
  "RPAR",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "PLUS",
  "ID",
  "STRING_LITERAL"
  };
}

